---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  shellcheck:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.md"
exclude_paths:
- lib/
- node_modules/
- test/
- coverage/
- CHANGELOG.md
